# eBay Used Car Listings

## Introduction

This project cleans and explores a sample of 50,000 used car listings scraped from *eBay Kleinanzeigen*, the classifieds section of the German eBay website, in March and April 2016. The original dataset is available on [Kaggle](https://www.kaggle.com/datasets/sijovm/used-cars-data-from-ebay-kleinanzeigen).

The raw data is messy. Prices and odometer readings are stored as text, many categories are in German, and some values (such as cars registered in the year 1000) are impossible. The goals of this notebook are to:

* clean the data so it is ready for analysis
* explore the cleaned listings, starting with how prices compare across German car brands

The notebook uses `pandas` and `numpy`.

In [1]:
import pandas as pd
import numpy as np

autos = pd.read_csv("Data/autos.csv", encoding='latin1')

In [2]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÜV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [3]:
autos.info()
autos.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          50000 non-null  object
 1   name                 50000 non-null  object
 2   seller               50000 non-null  object
 3   offerType            50000 non-null  object
 4   price                50000 non-null  object
 5   abtest               50000 non-null  object
 6   vehicleType          44905 non-null  object
 7   yearOfRegistration   50000 non-null  int64
 8   gearbox              47320 non-null  object
 9   powerPS              50000 non-null  int64
 10  model                47242 non-null  object
 11  odometer             50000 non-null  object
 12  monthOfRegistration  50000 non-null  int64
 13  fuelType             45518 non-null  object
 14  brand                50000 non-null  object
 15  notRepairedDamage    40171 non-null  object
 16  dateCreated          50000 non-null  object
 17  nrOfPictures         50000 non-null  int64
 18  postalCode           50000 non-null  int64
 19  lastSeen             50000 non-null  object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Taking an initial look at the imported `autos` data, we can see that this is a decently sized dataset. We have 20 columns with 50,000 entries. Moreover, most of the columns are text columns, with only a handful being integers.

## Data Cleaning

### Cleaning Columns

In [4]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [5]:
column_names = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest', 'vehicle_type', 'registration_year', 
                'gear_box', 'power_ps', 'model', 'odometer', 'registration_month', 'fuel_type', 'brand', 'unrepaired_damage', 'ad_created',
                'num_photos', 'postal_code', 'last_seen']
autos.columns = column_names

autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_photos,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Taking a look at the initial dataframe, there are some things to note. Most importantly, we see that the data has some column names that are a bit clunky and can be renamed for clarity. We also noted that the column names are in camelCase instead of snake_case, which is the convention preferred in pandas. So we reformatted the column names to snake_case.

### Data Exploration for Cleaning
After loading the data and renaming the columns, we can now dive into the data to inspect data quality and clean it. The first two steps we perform are to:
* drop any text columns where most of the values are the same
* clean and convert any text columns that store numeric data

In [6]:
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gear_box,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_photos,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-04-02 11:37:04,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

After looking at the description table, we can see several characteristics of the columns that can help us decide how to clean our dataframe. The `seller` and `offer_type` columns have nearly all entries as the same value. We can drop these columns. The `num_photos` column looks a bit strange with 50,000 entries, but only one unique value. We will need to investigate more. Lastly, it looks like there are some numeric columns with text in them: `odometer` and `price`.

In [7]:
autos["num_photos"].value_counts()

num_photos
0    50000
Name: count, dtype: int64

The `num_photos` column has an entry for every row, but every entry is 0. We will delete this column and the other two columns mentioned previously.

In [8]:
autos = autos.drop(["num_photos", "seller", "offer_type"], axis=1)

We will clean the two columns with values stored as text: `odometer` and `price`. We will strip the non-numeric characters and convert them to the proper data types. We will also rename the `odometer` column to `odometer_km` to show that the readings are in kilometers, not miles, since the data source is scraped from a country where they use the metric system.

In [9]:
autos["price"] = (autos["price"]
                    .str.replace("$", "")
                    .str.replace("," , "")
                    .astype(int)
                  )
autos["price"].head()

0    5000
1    8500
2    8990
3    4350
4    1350
Name: price, dtype: int64

In [10]:
autos["odometer"] = (autos["odometer"]
                        .str.replace("km", "")
                        .str.replace("kms", "")
                        .str.replace(',' , '')
                        .astype(int)
                     )

autos.rename({"odometer": "odometer_km"}, axis=1, inplace=True)
autos["odometer_km"].head()

0    150000
1    150000
2     70000
3     70000
4    150000
Name: odometer_km, dtype: int64

### Taking a Deeper Look at Columns

In [11]:
print(autos["odometer_km"].unique().shape)

print(autos["odometer_km"].describe())

print(autos["odometer_km"].value_counts())

(13,)
count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64
odometer_km
150000    32424
125000     5170
100000     2169
90000      1757
80000      1436
70000      1230
60000      1164
50000      1027
5000        967
40000       819
30000       789
20000       784
10000       264
Name: count, dtype: int64

Taking a look at the statistics of the `odometer_km` column, we can see that this column is well rounded to the closest 10,000 km. This could mean the sellers picked from preset ranges while listing them. Notably, there are a lot more high mileage vehicles, 150k km having more than 32,000 instances.

In [12]:
print(autos["price"].unique().shape)

print(autos["price"].describe())

print(autos["price"].value_counts())

(2357,)
count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64
price
0        1421
500       781
1500      734
2500      643
1000      639
         ...
414         1
79933       1
5198        1
18890       1
16995       1
Name: count, Length: 2357, dtype: int64

Taking a look at the `price` column, it seems like the prices are also well rounded, despite there being 2,357 unique values, significantly more than the 13 unique values in the `odometer_km` column. 

Considering eBay is an auction site, it makes sense that there are entries with only `$1`, however it is less likely that the cars with over `$350,000` are realistic because they increase at sporadic intervals with interesting numeric sequences. Something to consider is deleting the entries with `$0` because it is hard to think of an auction happening without a bid, and these `$0` entries only account for about 3% of the data.

In [13]:
autos["price"].value_counts().sort_index(ascending=False).head(20)

price
99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
350000      1
345000      1
299000      1
295000      1
265000      1
259000      1
250000      1
220000      1
198000      1
197000      1
Name: count, dtype: int64

In [14]:
autos["price"].value_counts().sort_index(ascending=True).head(20)

price
0     1421
1      156
2        3
3        1
5        2
8        1
9        1
10       7
11       2
12       3
13       2
14       1
15       2
17       3
18       1
20       4
25       5
29       1
30       7
35       1
Name: count, dtype: int64

In [15]:
autos = autos[autos["price"].between(1,351000)]
autos["price"].describe()

count     48565.000000
mean       5888.935591
std        9059.854754
min           1.000000
25%        1200.000000
50%        3000.000000
75%        7490.000000
max      350000.000000
Name: price, dtype: float64

Taking a look at the filtered `price` column, we can see much more realistic statistics. The standard deviation also dropped sharply, from about 481,000 to about 9,000, now that the extreme outliers are gone.

### Exploring Date Columns

There are several columns with date information: 
- `date_crawled`
- `registration_month`
- `registration_year`
- `ad_created`
- `last_seen`

Two of these columns are considered numeric, the other three as strings. To investigate the date columns, we will first look at how the three string columns are formatted.

In [16]:
autos[['date_crawled', "ad_created", "last_seen"]][0:5]

          date_crawled           ad_created            last_seen
0  2016-03-26 17:47:46  2016-03-26 00:00:00  2016-04-06 06:45:54
1  2016-04-04 13:38:56  2016-04-04 00:00:00  2016-04-06 14:45:08
2  2016-03-26 18:57:24  2016-03-26 00:00:00  2016-04-06 20:15:37
3  2016-03-12 16:58:10  2016-03-12 00:00:00  2016-03-15 03:16:28
4  2016-04-01 14:38:50  2016-04-01 00:00:00  2016-04-01 14:38:50

The non-numeric date columns are in YYYY-MM-DD format with the timestamp after it. We can select only the date part of the data entry using the `.str[:n]` method. We can also look at percentages instead of counts by passing `normalize=True` to `.value_counts()`, and sort the results by date with `.sort_index()`.

In [17]:
(autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_index())

date_crawled
2016-03-05    0.025327
2016-03-06    0.014043
2016-03-07    0.036014
2016-03-08    0.033296
2016-03-09    0.033090
2016-03-10    0.032184
2016-03-11    0.032575
2016-03-12    0.036920
2016-03-13    0.015670
2016-03-14    0.036549
2016-03-15    0.034284
2016-03-16    0.029610
2016-03-17    0.031628
2016-03-18    0.012911
2016-03-19    0.034778
2016-03-20    0.037887
2016-03-21    0.037373
2016-03-22    0.032987
2016-03-23    0.032225
2016-03-24    0.029342
2016-03-25    0.031607
2016-03-26    0.032204
2016-03-27    0.031092
2016-03-28    0.034860
2016-03-29    0.034099
2016-03-30    0.033687
2016-03-31    0.031834
2016-04-01    0.033687
2016-04-02    0.035478
2016-04-03    0.038608
2016-04-04    0.036487
2016-04-05    0.013096
2016-04-06    0.003171
2016-04-07    0.001400
Name: proportion, dtype: float64

In [18]:
(autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_values())

date_crawled
2016-04-07    0.001400
2016-04-06    0.003171
2016-03-18    0.012911
2016-04-05    0.013096
2016-03-06    0.014043
2016-03-13    0.015670
2016-03-05    0.025327
2016-03-24    0.029342
2016-03-16    0.029610
2016-03-27    0.031092
2016-03-25    0.031607
2016-03-17    0.031628
2016-03-31    0.031834
2016-03-10    0.032184
2016-03-26    0.032204
2016-03-23    0.032225
2016-03-11    0.032575
2016-03-22    0.032987
2016-03-09    0.033090
2016-03-08    0.033296
2016-04-01    0.033687
2016-03-30    0.033687
2016-03-29    0.034099
2016-03-15    0.034284
2016-03-19    0.034778
2016-03-28    0.034860
2016-04-02    0.035478
2016-03-07    0.036014
2016-04-04    0.036487
2016-03-14    0.036549
2016-03-12    0.036920
2016-03-21    0.037373
2016-03-20    0.037887
2016-04-03    0.038608
Name: proportion, dtype: float64

Taking a look at the sorted percentage outputs, it looks like most of the data was crawled between March and April 2016. The percentages show that the distribution is roughly uniform, with no single day exceeding 4% of the listings.

In [19]:
autos["last_seen"].str[:10].value_counts(normalize=True, dropna=False).sort_index()

last_seen
2016-03-05    0.001071
2016-03-06    0.004324
2016-03-07    0.005395
2016-03-08    0.007413
2016-03-09    0.009595
2016-03-10    0.010666
2016-03-11    0.012375
2016-03-12    0.023783
2016-03-13    0.008895
2016-03-14    0.012602
2016-03-15    0.015876
2016-03-16    0.016452
2016-03-17    0.028086
2016-03-18    0.007351
2016-03-19    0.015834
2016-03-20    0.020653
2016-03-21    0.020632
2016-03-22    0.021373
2016-03-23    0.018532
2016-03-24    0.019767
2016-03-25    0.019211
2016-03-26    0.016802
2016-03-27    0.015649
2016-03-28    0.020859
2016-03-29    0.022341
2016-03-30    0.024771
2016-03-31    0.023783
2016-04-01    0.022794
2016-04-02    0.024915
2016-04-03    0.025203
2016-04-04    0.024483
2016-04-05    0.124761
2016-04-06    0.221806
2016-04-07    0.131947
Name: proportion, dtype: float64

The `last_seen` value describes when the car was last seen by the crawler. For most of the data the entries are probably last seen because the car was sold. 

One thing to note is the last 3 values of `last_seen` percentage. This is probably because this was when the crawler last saw the entry, but the car was not yet sold by then. These dates are still good to work with, though we may want to exclude them in future analyses.

In [20]:
autos["ad_created"].str[:10].value_counts(normalize=True, dropna=False).sort_index()

ad_created
2015-06-11    0.000021
2015-08-10    0.000021
2015-09-09    0.000021
2015-11-10    0.000021
2015-12-05    0.000021
                ...
2016-04-03    0.038855
2016-04-04    0.036858
2016-04-05    0.011819
2016-04-06    0.003253
2016-04-07    0.001256
Name: proportion, Length: 76, dtype: float64

The `ad_created` variable has a lot of unique values, 76. A lot of these values are seen in March and April. Interestingly, there are a few lingering old ads, the oldest being from June 2015, around 9 months before the crawl.

In [21]:
autos["registration_year"].describe()

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

Taking a look at another time variable, the `registration_year` variable, we come to interesting and incorrect data. Taking a look at the minimum value of the registration year, it says the car was registered in 1000; this was well before cars were invented. Additionally, the maximum value seen is 9999, many thousands of years still into the future.

### Dealing with Incorrect Registration Data

In [22]:
autos.loc[autos["registration_year"] > 1930, "registration_year"].value_counts()

registration_year
2000    3156
2005    2936
1999    2897
2004    2703
2003    2699
        ...
1931       1
1948       1
6200       1
4100       1
9000       1
Name: count, Length: 88, dtype: int64

In [23]:
autos.loc[autos["registration_year"] < 2016, "registration_year"].value_counts()

registration_year
2000    3156
2005    2936
1999    2897
2004    2703
2003    2699
        ...
1929       1
1943       1
1931       1
1948       1
1001       1
Name: count, Length: 81, dtype: int64

Realistically speaking, since the data was scraped in 2016, there should be no `registration_year` for values above 2016. Moreover, since cars were popularized around the 1930s, a good minimum value for the `registration_year` range is 1930. We want to double check the percentage of rows outside this range.

In [24]:
(~autos["registration_year"].between(1930, 2016)).sum() / autos.shape[0]

np.float64(0.038937506434675175)

Taking a look at the percentage of values that are not between 1930 and 2016, we can see that these are good parameters. Less than 4% of the data lies outside the upper and lower bounds.

In [25]:
autos = autos[autos["registration_year"].between(1930, 2016)]
autos["registration_year"].value_counts(normalize=True)

registration_year
2000    0.067618
2005    0.062904
1999    0.062069
2004    0.057912
2003    0.057827
          ...
1939    0.000021
1948    0.000021
1938    0.000021
1953    0.000021
1931    0.000021
Name: proportion, Length: 75, dtype: float64

Taking a look at the cleaned registration year, we can see that most of the cars were registered in recent years.

### Cleaning German Words

Several text columns still contain German words. Starting with `vehicle_type`, we will map each German category to its English equivalent. Categories that are already English (`bus`, `coupe`, `suv`) are left as they are.

In [ ]:
autos["vehicle_type"].value_counts(dropna=False)

In [ ]:
vehicle_type_english = {
    "limousine": "sedan",
    "kleinwagen": "small_car",
    "kombi": "station_wagon",
    "cabrio": "convertible",
    "andere": "other",
}

autos["vehicle_type"] = autos["vehicle_type"].replace(vehicle_type_english)
autos["vehicle_type"].value_counts(dropna=False)

Next we translate `gear_box`, `fuel_type`, and `unrepaired_damage` the same way. Values that are already English or are abbreviations (`diesel`, `lpg`, `cng`, `hybrid`) are left as they are.

In [ ]:
gear_box_english = {
    "manuell": "manual",
    "automatik": "automatic",
}

fuel_type_english = {
    "benzin": "petrol",
    "elektro": "electric",
    "andere": "other",
}

unrepaired_damage_english = {
    "ja": "yes",
    "nein": "no",
}

autos["gear_box"] = autos["gear_box"].replace(gear_box_english)
autos["fuel_type"] = autos["fuel_type"].replace(fuel_type_english)
autos["unrepaired_damage"] = autos["unrepaired_damage"].replace(unrepaired_damage_english)

for col in ["gear_box", "fuel_type", "unrepaired_damage"]:
    print(autos[col].value_counts(dropna=False), "\n")

## Data Exploration

### Price by Brand

In [33]:
autos["brand"].value_counts(normalize=True)

brand
volkswagen        0.211295
bmw               0.110040
opel              0.107555
mercedes_benz     0.096478
audi              0.086579
ford              0.069889
renault           0.047135
peugeot           0.029845
fiat              0.025646
seat              0.018276
skoda             0.016412
nissan            0.015276
mazda             0.015190
smart             0.014162
citroen           0.014012
toyota            0.012705
hyundai           0.010027
sonstige_autos    0.009791
volvo             0.009149
mini              0.008763
mitsubishi        0.008227
honda             0.007842
kia               0.007070
alfa_romeo        0.006642
porsche           0.006128
suzuki            0.005935
chevrolet         0.005699
chrysler          0.003514
dacia             0.002635
daihatsu          0.002507
jeep              0.002271
subaru            0.002143
land_rover        0.002100
saab              0.001650
jaguar            0.001564
daewoo            0.001500
trabant           0.001371
rover             0.001328
lancia            0.001071
lada              0.000578
Name: proportion, dtype: float64

Taking a look at the percentages for the car brands in the list, we can see the largest car brands. The top 5 brands in the list are manufactured in Germany: `volkswagen`, `bmw`, `opel`, `mercedes_benz`, and `audi`. The other German brands are `smart`, `porsche`, and `trabant`. We could investigate the aftermarket performance for German car brands by looking at the price ratio.

In [ ]:
brands_list = ["volkswagen", "bmw", "opel", "mercedes_benz", 
          "audi", "smart", "porsche", "trabant"]
german_brands = autos[autos["brand"].isin(brands_list)]
print(german_brands["brand"].unique())

['bmw' 'smart' 'mercedes_benz' 'audi' 'opel' 'porsche' 'trabant']

In [ ]:
brand_mean_prices = {}

for brand in brands_list:
    brand_only = german_brands[german_brands["brand"] == brand]
    mean_price = brand_only["price"].mean()
    brand_mean_prices[brand] = int(mean_price)

print(brand_mean_prices)

Looking at the mean prices, the German brands fall into three clear groups:
* **Luxury:** `porsche` is in a league of its own, with a mean price of about `$45,600`, roughly five times more than any other German brand.
* **Premium:** `audi`, `mercedes_benz`, and `bmw` are close together, between about `$8,300` and `$9,300`.
* **Budget:** `volkswagen` sits in the middle at about `$5,400`, while `smart`, `opel`, and `trabant` are the cheapest at under `$3,600`.

## Conclusion

In this project we cleaned and explored 50,000 used car listings from eBay Kleinanzeigen. The raw data needed a lot of work before it could be analyzed:
* Column names were converted from camelCase to snake_case.
* The `seller`, `offer_type`, and `num_photos` columns were dropped because almost every row had the same value.
* `price` and `odometer` were stored as text, so we stripped the `$`, `km`, and commas and converted them to integers.
* Listings with unrealistic prices (`$0` or over `$350,000`) and impossible registration years (before 1930 or after 2016) were removed.
* German category values in `vehicle_type`, `gear_box`, `fuel_type`, and `unrepaired_damage` were translated to English.

After cleaning, we kept 46,674 listings, about 93% of the original data.

From exploring the cleaned data, we found that:
* Listings were crawled fairly evenly from early March to early April 2016, and most ads were created in the same window.
* Most cars have high mileage, with nearly two thirds of listings at the 150,000 km maximum.
* German brands dominate the site. The eight German brands make up about 63% of all listings, and `volkswagen` alone accounts for about 21%.
* Among German brands, price follows reputation. `porsche` is by far the most expensive, `audi`, `mercedes_benz`, and `bmw` form a premium tier, and `opel` and `trabant` are the cheapest.

One limitation is that we compared **mean** prices, which can be pulled up by a few very expensive listings, and some brands (such as `trabant`, with only 64 listings) have small samples. Next steps could include comparing median prices, checking whether mileage explains the price gaps between brands, and looking at how unrepaired damage affects price.